### ISSUE TITLE
Stop bundling Mopidy.js

### ISSUE THREAD

**Issue by jodal** [mopidy/mopidy#1460]
I propose that as of Mopidy 3.0 we stop bundling Mopidy.js.

There are several arguments supporting this:
- There is no huge benefit in shipping Mopidy with a "compatible" Mopidy.js, as we have never broken the WebSocket API in the more than three years since introducing it. All released versions of Mopidy.js still works with the latest Mopidy release, AFAIK.
- Modern web stacks provides proper dependency management through npm and builds single-file app bundles using Browserify or Webpack. Including the Mopidy.js we ship with a tag in your HTML is increasingly rare.
- Breaking the API of a bundled Mopidy.js immediately breaks all clients using it that have not been updated accordingly. By not providing a version of Mopidy.js bundled with Mopidy all clients have to ship their own copy and decides themselves when to upgrade to a newer version of Mopidy.js. Thus, we're free to make new releases of Mopidy.js, including breaking changes like changing the default calling convention or replacing when.js with standard ES6 Promises and Bane with a standard EventEmitter. A lot has happened in the JavaScript world since Mopidy.js was conceived.
- Given the source of the mopidy Debian package, you cannot rebuild the bundled Mopidy.js JavaScript files, thus breaking Debian policy. To package this properly, Mopidy.js would have to be packaged as its own Debian package which builds Mopidy.js from source. However, the Grunt and Browserify build tools are not currently packaged in Debian, so this isn't straight forward. I've looked into simplifying the build, maybe using browserify-lite (which is packaged) but it's hard to accomplish this and keep the module working in both the browser and on Node.js.

Status of known/popular clients:
- [ ] Mopidy-API-Explorer: Uses our **bundled** mopidy.js. Needs to be changed before Mopidy 3. See dz0ny/mopidy-api-explorer#2.
- [x] Mopidy-Mobile: Installs Mopidy.js from npmjs.org using **Bower**.
- [x] Mopidy-Moped: **Vendors** mopidy.js into its own source tree.
- [x] Mopidy-Mopify: **Vendors** mopidy.js into its own source tree.
- [x] Mopidy-Musicbox-Webclient: Uses our **bundled** mopidy.js. Needs to be changed before Mopidy 3. See pimusicbox/mopidy-musicbox-webclient#175.
- [ ] Mopidy-Party: Uses our **bundled** mopidy.js. Needs to be changed before Mopidy 3. See https://github.com/Lesterpig/mopidy-party/issues/21

Other than updating clients using the bundled copy, we need to:
- [x] Update Mopidy.js' README.
- [ ] Make a new release to npmjs.org with said README.
- [x] Decide if we're just going to release to npm, or if we need to provide ready-built JS files e.g. via GitHub Releases. For simplicity, I'd like to start with just npm.
- [x] Update the https://docs.mopidy.com/en/latest/api/js/#getting-the-library-for-browser-use docs section accordingly.
- [x] Update `MopidyAppTest.test_should_return_static_files` to use another file for the test.
- [x] Remove bundled files in `mopidy/http/data`.

**Comment by jodal** [comment]
Mopidy.js readme has been updated to not refer to files included in Mopidy or hosted by Mopidy.

The built files has been uploaded to [Mopidy.js' GitHub releases page](https://github.com/mopidy/mopidy.js/releases).

A new release to npm has not been made, as the build system is so outdated that I can't even manage to install it.
