### ISSUE TITLE
Move to Tornado 5

### ISSUE THREAD

**Issue by kingosticks** [mopidy/mopidy#1798]
This tracks the progress of supporting Tornado 5.

- [x] MIgrate to CircleCI where we can ensure we run a version of Python 2.7 that's supported by Tornado 5 (#1797)
- [x] Support IOLoop changes (#1716, #1796)
- [ ] Check web extensions (https://github.com/jaedb/Iris/issues/432)
