### ISSUE TITLE
Documentation improvements

### ISSUE THREAD

**Issue by adamcik** [mopidy/mopidy#426]
Following is a list of things I noticed while reading through most of our docs, mark things as done as they get fixed, add strikeout and mark as done for won't fix. Not critical for release, but would be nice to try and fix these and any other nitpicks we come across.

General
- [x] ~~Mention that MPRIS will not be run outside of X in the higher level docs?~~ It is mentioned in the MPRIS clients docs.
- [x] Update copyright years, still 2012
- [x] Look at wording of changelog for 0.14

Contributing
- [x] ~~Add glossary for terms such as tracklist, i.e. document more of our vocabulary~~ Moved to #430

Installation
- [x] AUR tracks latest not develop
- [x] Notes about drawbacks on raspi could be removed or moved to a less prominent 
  position. History for raspi support hidden on the bottom of the page or sub-page?

Troubleshooting
- [x] Encourage use of pastebins when using `--show-config`, could mention piping to 
  xclip?
- [x] ~~Should we keep `ps ax | grep mopidy | grep -v grep | cut -d’ ’ -f1'` or just put `$PID_OF_MOPIDY` instead? Have both versions perhaps?~~ The goal is to help people find the PID. We can simplify it if we start to write a pid file.

Clients
- [x] Make sure distinction between WS and MPD web clients is clear?
- [x] ~~Add note/plea directed at MPD client authors to not query for everything to do local search.~~ If they're reading our web pages, then they're hopefully testing their client with Mopidy and will avoid doing assumptions that only work for local music.
- [x] Remove spotify from rygel examples as it probably just confuses people.

Config
- [x] `audio/mixer` should mention that default is `autoaudiomixer` and that it attempts to pick a sane mixer
- [x] `proxy/username` etc `s/if required/if needed`
- [x] Graphviz for config stuff doesn't seem worth it.
- [x] Serialize part of config schema needs docs.

Exension development
- [x] ~~Mention custom uri use in extension docs.~~ Moved to #429 
- [x] Mention why we use `unicode_literals` in extensions docs?
- [x] ~~Add example of gst element that implements the uri interface.~~ Moved to #429 
- [x] ~~Encourage extension writers to not use appsrc, but custom elements, bins.~~ Moved to #429 
- [x] ~~Mention that greenlets etc might be a bad mix with actors?~~ They're not, really. It's just gevent 0.x that's a bad mix with anything related to threads.
- [x] Should we note that we start the actors, not the extension writers?
- [x] Do we link to frontend/backend APIs in the extension docs?
- [x] ~~Note that extension writers should be using `mopidy.config` not `types` directly?~~ All examples use `mopidy.config` directly.
- [x] ~~Note that we don't yet have a shareable httpd?~~ I think including that in the docs will just confuse people as they don't know why they would want that.

References
- [x] Mention that copies can be made of models.
- [x] Docs for audio listener should enumerate the events `on_event` passes.
